### PR TITLE
Milestone friendships v1

### PR DESCRIPTION
**Pull request by crappypapa**
We have attempted to create User methods and associations between users to implement features of Friendships such as 

- Accepting friend requests
- Rejecting friend requests
- Showing pending friend requests

Also we have added some tests for our app.

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- User model has_many :friendships :+1: 
- The User model has many inverted_friendships :100: 
- Friendship model belongs_to :user :1st_place_medal: 
-  Friendship model belongs_to :friend, class_name: "User" :+1: 

To improve :factory_worker: [REQUIRED]:

- [x] User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ]  `Posts timeline` includes posts written by `logged-in user and their friends `([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Please add test units for `associations` and `event managment features`. Don't forget to add negative cases.

Nice to have:

- [ ] Read about n+1 and make sure there are no n + 1 queries in index views [Recommended article.](https://medium.com/@bretdoucette/n-1-queries-and-how-to-avoid-them-a12f02345be5)
- [ ] User can accept and reject friend requests from the users index page.
- [ ] The user can see the friendship status when browsing other user show pages or the users index page.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Happy coding
Rindra Josia

**Comment by crappypapa** [comment]
I have tried to implement all the required changes suggested even though I feel the milestone in particular was to deal mainly with the model and associations.

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- User can invite friends :+1: 
- User can see friendships requests :100: 
- User can accept friendship request to start friendship :1st_place_medal: 
- User can reject a friendship request :+1: 
- There is a button to invite user to friendship `on users list page` :1st_place_medal: 
- Posts timeline includes posts written by logged-in user and their friends  :1st_place_medal: 

To improve :factory_worker: [REQUIRED]:

- [ ] There is a `button` to invite user to friendship `on single user page` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Please add more test units. Keep in mind that there are two ways to test software, namely Positive Testing, and Negative Testing. It will be perfect if you add also test for negative cases.

Nice to have:

- [ ]  

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Happy coding
Rindra Josia

**Review by afanimartin — APPROVED** [review]
## Approved 👏🏿 👏🏿 👏🏿 
Nice work making the requested changes. You may merge and proceed to the next project.

### Martin Afani
#### Slack: whiz25

**Review by afanimartin — APPROVED** [review]
## Approved 👏🏿 👏🏿 👏🏿 
Nice work making the requested changes. You may merge and proceed to the next project.

### Martin Afani
#### Slack: whiz25

**Pull request merged**
