### PR TITLE
Data Architecture

### PR DESCRIPTION
**Pull request by crappypapa**
We added an ERD diagram to show the relationship and association between the following models listed below of our app.

- User
- Comment
- Post
- Like
- Friendship

### CODE REVIEW

**Review by MkrtichSargsyan — COMMENTED** [review]
## _Status:_ Invalid submission warning

## Hello Guys


This Code Review Request will be marked as invalid in your Dashboard because the actions on Github were not set up properly. Follow the steps below on the forked repo:

* Enable the GitHub Actions in the Actions tab.
* Create the feature/branch and push.
* Start working on the milestone as usual.
* Open a PR from the feature/branch when the work is done.


Please make the necessary changes and submit another code review request once you are ready! :slightly_smiling_face:.


> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Comment by crappypapa** [comment]
I have activated the Github workflows for the repository.

**Comment by crappypapa** [comment]
I have made an attempt to fix the ERD diagram previously submitted and the file name for the updated diagram is ```Ror Social Media_ Lucidchart 02.png```

**Review by oloomoses — CHANGES_REQUESTED** [review]
**Hello @crappypapa, your ERD looks impressive :muscle: **
Well done on implementing some of the suggested changes. 
However, the relationship between  user and friendship is not correct and needs some amendments

- [x] The relationship for the mutual friendship should look like this
Screenshot from 2021-04-16 14-56-58

**Kindly implement the above change before submitting another review.**
**Feel free to reach me on slack or leave a comment while mentioning me and I will be happy to reply**

_Slack: Oloo Moses_

**Comment by crappypapa** [comment]
Thank you!
@DeliceLydia 
@oloomoses 
@MkrtichSargsyan 
@descholar-ceo

**Pull request merged**
